"use client";
import { useState } from "react";
import { C } from "../constants/colors";
import { CLIENTS } from "../constants/clients";
import { Card, SectionTitle, Btn, ProgressBar } from "../shared";
import { buildReportData } from "./reportDataBuilder";
import ResultsBlock from "./ResultsBlock";
import UpsellBlock from "./UpsellBlock";
import { narrateScore, narrateScoreDelta, narratePosition, narrateReviews, narratePhotos, narrateSection, narrateWhatWeDid, narrateNextMonth, narrateMonthSummary, narrateInteractions } from "./reportNarrative";
import { downloadReportPDF } from "./reportPDF";

// ── Date helpers ──
function formatDate(d) { return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }); }
function toInputDate(d) { return d.toISOString().split("T")[0]; }
function daysBetween(a, b) { return Math.max(1, Math.round(Math.abs(b - a) / 86400000)); }

export default function ClientReports({ client, allClients }) {
  const clients = allClients || CLIENTS;
  const [reportClient, setReportClient] = useState(clients[0]?.id || client.id || "1");
  const [report, setReport] = useState(null);
  const [generating, setGenerating] = useState(false);

  // Date range
  const today = new Date();
  const [dateFrom, setDateFrom] = useState(toInputDate(new Date(today.getFullYear(), today.getMonth(), 1)));
  const [dateTo, setDateTo] = useState(toInputDate(today));

  // Bulk
  const [bulkMode, setBulkMode] = useState(false);
  const [selectedClients, setSelectedClients] = useState([]);
  const [bulkReports, setBulkReports] = useState([]);

  // Section visibility filter
  const ALL_SECTIONS = [
    { id: "score",        label: "Profile Score" },
    { id: "breakdown",    label: "Score Breakdown" },
    { id: "interactions", label: "Profile Interactions" },
    { id: "reviews",      label: "Customer Reviews" },
    { id: "photos",       label: "Photos" },
    { id: "competitors",  label: "Competitors" },
    { id: "timeline",     label: "6-Month Journey" },
    { id: "actions",      label: "Actions Needed" },
    { id: "plan",         label: "Next Period Plan" },
    { id: "upsell",       label: "Growth Proposal" },
  ];
  const [visibleSections, setVisibleSections] = useState(ALL_SECTIONS.map(s => s.id));
  const toggleSection = (id) => setVisibleSections(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);
  const show = (id) => visibleSections.includes(id);

  const rc = clients.find(c => String(c.id) === String(reportClient)) || clients[0];
  const periodDays = daysBetween(new Date(dateFrom), new Date(dateTo));
  const periodLabel = `${formatDate(new Date(dateFrom))} — ${formatDate(new Date(dateTo))} (${periodDays} days)`;

  // Presets
  const setPreset = (days) => {
    const end = new Date();
    const start = new Date();
    start.setDate(end.getDate() - days);
    setDateFrom(toInputDate(start));
    setDateTo(toInputDate(end));
  };

  const generate = () => {
    setGenerating(true);
    setTimeout(() => {
      setReport(buildReportData(rc, { dateFrom, dateTo, periodDays }));
      setGenerating(false);
    }, 500);
  };

  const generateBulk = () => {
    if (selectedClients.length === 0) return;
    setGenerating(true);
    const results = selectedClients.map(cid => {
      const cl = clients.find(c => String(c.id) === String(cid));
      return cl ? { client: cl, data: buildReportData(cl, { dateFrom, dateTo, periodDays }) } : null;
    }).filter(Boolean);
    setBulkReports(results);
    setGenerating(false);
  };

  const toggleClient = (id) => setSelectedClients(prev => prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]);

  const copyReport = () => {
    if (!report) return;
    const lines = [
      `REPORT — ${report.name}`,
      `${report.category} in ${report.city}`,
      `Period: ${periodLabel}`,
      "",
      `Profile Score: ${report.overall}/100 (${report.scoreDelta >= 0 ? "+" : ""}${report.scoreDelta})`,
      `Reviews: ${report.reviews.total} | Rating: ${report.reviews.average}★ | Reply Rate: ${report.reviews.responseRate}%`,
      `Photos: ${report.photos.total} | Position: ${report.estPosition}`,
      `Interactions: ${report.interactions.calls} calls | ${report.interactions.routes} directions | ${report.interactions.clicks} clicks`,
      "",
      "SCORE BREAKDOWN:",
      ...report.sections.map(s => `${s.name}: ${s.score}/100 (was ${s.prev})`),
      "",
      "ACTIONS:",
      ...report.quickWins.map((w, i) => `${i + 1}. ${w.action}\n   Why: ${w.why}\n   How: ${w.how}`),
      "",
      "NEXT PERIOD:",
      ...report.monthPriorities.map((p, i) => `${i + 1}. ${p.title} — ${p.kpi}`),
      "",
      `Generated by Zenith — ${report.dateStr}`,
    ];
    navigator.clipboard?.writeText(lines.join("\n")).catch(() => {});
  };

  // ══════════════════════════════════════
  // REPORT RENDER (unified)
  // ══════════════════════════════════════
  const renderReport = (data) => {
    const scoreColor = data.overall >= 80 ? C.green : data.overall >= 50 ? C.yellow : C.red;
    const isLong = periodDays >= 25; // 30-day reports show more detail

    return (
      <div style={{ display: "flex", flexDirection: "column", gap: 14 }}>

        {/* Cover */}
        <div style={{ background: `linear-gradient(135deg,${C.blue}18,${C.cyan}0d)`, border: `1px solid ${C.blue}33`, borderRadius: 14, padding: "28px 32px" }}>
          <div style={{ fontSize: 10, color: C.textMuted, fontWeight: 700, letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 8 }}>
            {periodDays <= 15 ? "Biweekly Report" : "Monthly Report"} — {periodDays} days
          </div>
          <div style={{ fontSize: 24, fontWeight: 900, color: C.text, marginBottom: 4 }}>{data.name}</div>
          <div style={{ fontSize: 12, color: C.textMuted, marginBottom: 6 }}>{data.category} in {data.city}</div>
          <div style={{ fontSize: 11, color: C.cyan, fontWeight: 600, marginBottom: 16 }}>{periodLabel}</div>
          <div style={{ fontSize: 14, color: C.textDim, lineHeight: 1.7 }}>{narrateMonthSummary(data)}</div>
        </div>

        {/* Profile Score — before / after */}
        {show("score") && <Card>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 14 }}>Profile Health</div>
          <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 20, marginBottom: 14 }}>
            <div style={{ textAlign: "center" }}>
              <div style={{ fontSize: 10, color: C.textMuted, fontWeight: 600, marginBottom: 4 }}>Before</div>
              <div style={{ fontSize: 32, fontWeight: 900, color: C.textMuted }}>{data.prevScore}</div>
            </div>
            <div style={{ fontSize: 24, color: data.scoreDelta >= 0 ? C.green : C.red, fontWeight: 900 }}>→</div>
            <div style={{ textAlign: "center" }}>
              <div style={{ fontSize: 10, color: scoreColor, fontWeight: 600, marginBottom: 4 }}>Now</div>
              <div style={{ fontSize: 42, fontWeight: 900, color: scoreColor }}>{data.overall}</div>
            </div>
            <div style={{ fontSize: 14, fontWeight: 700, color: data.scoreDelta >= 0 ? C.green : C.red, background: `${data.scoreDelta >= 0 ? C.green : C.red}15`, padding: "6px 12px", borderRadius: 8 }}>
              {data.scoreDelta >= 0 ? "+" : ""}{data.scoreDelta}
            </div>
          </div>
          <div style={{ fontSize: 13, color: C.textDim, lineHeight: 1.7, textAlign: "center" }}>{narrateScore(data.overall)}</div>
        </Card>}

        {/* Score Breakdown */}
        {show("breakdown") && <Card>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 14 }}>Score Breakdown</div>
          {data.sections.map(s => {
            const delta = s.score - s.prev;
            const col = s.score >= 70 ? C.green : s.score >= 50 ? C.yellow : C.red;
            return (
              <div key={s.name} style={{ marginBottom: 16 }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 4 }}>
                  <span style={{ fontSize: 13, fontWeight: 600, color: C.text }}>{s.name}</span>
                  <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                    <span style={{ fontSize: 11, color: C.textMuted }}>was {s.prev}</span>
                    <span style={{ fontSize: 16, fontWeight: 900, color: col }}>{s.score}</span>
                    <span style={{ fontSize: 11, color: delta >= 0 ? C.green : C.red, fontWeight: 700 }}>{delta >= 0 ? "+" : ""}{delta}</span>
                  </div>
                </div>
                <ProgressBar value={s.score} color={col} />
                <div style={{ fontSize: 12, color: C.textDim, marginTop: 4, lineHeight: 1.6 }}>{narrateSection(s)}</div>
              </div>
            );
          })}
        </Card>}

        {/* Profile Interactions */}
        {show("interactions") && <Card>
          <ResultsBlock data={data} variant="detailed" />
        </Card>}

        {/* Reviews */}
        {show("reviews") && <Card>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 14 }}>Customer Reviews</div>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 10, marginBottom: 14 }}>
            {[
              { label: "Total", value: data.reviews.total, color: C.blue },
              { label: "Rating", value: data.reviews.average + "★", color: data.reviews.average >= 4.5 ? C.green : C.yellow },
              { label: "Reply Rate", value: data.reviews.responseRate + "%", color: data.reviews.responseRate >= 80 ? C.green : C.red },
              { label: "New", value: data.reviews.last30days, color: data.reviews.last30days >= 3 ? C.green : C.orange },
            ].map(m => (
              <div key={m.label} style={{ background: C.bg, borderRadius: 8, padding: "10px 12px", textAlign: "center" }}>
                <div style={{ fontSize: 9, color: C.textMuted, fontWeight: 700, letterSpacing: 0.5, textTransform: "uppercase", marginBottom: 5 }}>{m.label}</div>
                <div style={{ fontSize: 20, fontWeight: 900, color: m.color }}>{m.value}</div>
              </div>
            ))}
          </div>
          <div style={{ fontSize: 13, color: C.textDim, lineHeight: 1.7 }}>{narrateReviews(data.reviews)}</div>
        </Card>}

        {/* Photos */}
        {show("photos") && <Card>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 10 }}>Photos</div>
          <div style={{ display: "flex", gap: 14, alignItems: "center", marginBottom: 10 }}>
            <div style={{ fontSize: 32, fontWeight: 900, color: data.photos.total >= 20 ? C.green : data.photos.total >= 10 ? C.yellow : C.red }}>{data.photos.total}</div>
            <div>
              <div style={{ fontSize: 12, color: C.textMuted }}>photos on profile</div>
              <div style={{ fontSize: 11, color: data.photos.total > data.photos.prevTotal ? C.green : C.textMuted }}>
                {data.photos.total > data.photos.prevTotal ? `+${data.photos.total - data.photos.prevTotal} added` : "No new photos"}
              </div>
            </div>
          </div>
          <div style={{ fontSize: 13, color: C.textDim, lineHeight: 1.7 }}>{narratePhotos(data.photos)}</div>
        </Card>}

        {/* Competitor Comparison */}
        {show("competitors") && <Card>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 14 }}>Competitors</div>
          {data.competitors.map(comp => {
            const barW = Math.max(10, comp.score);
            return (
              <div key={comp.name} style={{ marginBottom: 12 }}>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 4 }}>
                  <span style={{ fontSize: 12, color: comp.isClient ? C.cyan : C.textDim, fontWeight: comp.isClient ? 700 : 400 }}>
                    {comp.isClient ? `★ ${data.name}` : comp.name}
                  </span>
                  <span style={{ fontSize: 13, fontWeight: 800, color: comp.isClient ? C.cyan : C.textMuted }}>{comp.score}</span>
                </div>
                <div style={{ height: 8, background: C.bg, borderRadius: 4, overflow: "hidden" }}>
                  <div style={{ width: `${barW}%`, height: "100%", background: comp.isClient ? C.cyan : `${C.textMuted}44`, borderRadius: 4 }} />
                </div>
              </div>
            );
          })}
          <div style={{ fontSize: 13, color: C.textDim, marginTop: 10, lineHeight: 1.7 }}>
            {narratePosition(data.estPosition, data.prevPosition)}
          </div>
        </Card>}

        {/* 6-Month Journey */}
        {show("timeline") && (
          <Card>
            <ResultsBlock data={data} variant="timeline" />
          </Card>
        )}

        {/* Actions */}
        {show("actions") && <Card>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 4 }}>Actions Needed</div>
          <div style={{ fontSize: 13, color: C.textDim, lineHeight: 1.7, marginBottom: 14 }}>{narrateWhatWeDid(data.quickWins)}</div>
          {data.quickWins.map((qw, i) => (
            <div key={i} style={{ display: "flex", gap: 14, padding: "12px 0", borderBottom: i < data.quickWins.length - 1 ? `1px solid ${C.border}` : "none" }}>
              <div style={{ width: 28, height: 28, borderRadius: 7, background: qw.impact === "high" ? `${C.orange}22` : `${C.blue}15`, color: qw.impact === "high" ? C.orange : C.blue, fontWeight: 900, fontSize: 12, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{qw.priority}</div>
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 700, fontSize: 13, color: C.text, marginBottom: 4 }}>{qw.action}</div>
                <div style={{ fontSize: 12, color: C.textMuted, lineHeight: 1.6, marginBottom: 4 }}><strong style={{ color: C.textDim }}>Why:</strong> {qw.why}</div>
                <div style={{ fontSize: 12, color: C.cyan, lineHeight: 1.6 }}><strong>How:</strong> {qw.how}</div>
                <div style={{ display: "flex", gap: 8, marginTop: 6 }}>
                  <span style={{ fontSize: 10, padding: "2px 8px", borderRadius: 4, background: `${C.textMuted}18`, color: C.textMuted }}>{qw.effort}</span>
                  <span style={{ fontSize: 10, padding: "2px 8px", borderRadius: 4, background: `${qw.impact === "high" ? C.orange : C.yellow}18`, color: qw.impact === "high" ? C.orange : C.yellow, fontWeight: 600 }}>{qw.impact === "high" ? "High Impact" : "Medium Impact"}</span>
                </div>
              </div>
            </div>
          ))}
        </Card>}

        {/* Next Period Plan */}
        {show("plan") && <Card style={{ border: `1px solid ${C.blue}22` }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.text, marginBottom: 14 }}>Plan for Next Period</div>
          {data.monthPriorities.map((p, i) => (
            <div key={i} style={{ display: "flex", gap: 14, padding: "12px 0", borderBottom: i < data.monthPriorities.length - 1 ? `1px solid ${C.border}` : "none" }}>
              <div style={{ width: 28, height: 28, borderRadius: 7, background: `${C.blue}22`, color: C.blue, fontWeight: 900, fontSize: 13, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>{i + 1}</div>
              <div style={{ flex: 1 }}>
                <div style={{ fontWeight: 700, fontSize: 13, color: C.text, marginBottom: 4 }}>{p.title}</div>
                <div style={{ fontSize: 12, color: C.textDim, lineHeight: 1.6, marginBottom: 4 }}>{p.description}</div>
                <div style={{ fontSize: 11, color: C.cyan, fontWeight: 600 }}>{p.kpi}</div>
              </div>
            </div>
          ))}
        </Card>}

        {/* Upsell / Growth Proposal */}
        {show("upsell") && (
          <Card style={{ border: `1px solid ${C.green}33` }}>
            <UpsellBlock data={data} />
          </Card>
        )}

        {/* Footer */}
        <div style={{ textAlign: "center", fontSize: 10, color: C.textMuted, padding: "8px 0" }}>
          {data.name} — {periodLabel} — Generated by Zenith
        </div>
      </div>
    );
  };

  // ══════════════════════════════════════
  // MAIN UI
  // ══════════════════════════════════════
  return (
    <div>
      <SectionTitle>Client Reports</SectionTitle>

      {/* Controls (when no report yet) */}
      {!report && !bulkReports.length && (
        <>
          <Card style={{ marginBottom: 16 }}>
            {/* Client selector */}
            <div style={{ marginBottom: 16 }}>
              <label style={{ fontSize: 10, color: C.textMuted, fontWeight: 700, display: "block", marginBottom: 5, textTransform: "uppercase", letterSpacing: 0.5 }}>Client</label>
              <select value={reportClient} onChange={e => setReportClient(e.target.value)}
                style={{ width: "100%", padding: "9px 12px", background: C.bg, border: `1px solid ${C.border}`, borderRadius: 7, color: C.text, fontSize: 13, outline: "none" }}>
                {clients.map(c => <option key={c.id} value={c.id}>{c.businessName || c.name}</option>)}
              </select>
            </div>

            {/* Date range */}
            <div style={{ marginBottom: 16 }}>
              <label style={{ fontSize: 10, color: C.textMuted, fontWeight: 700, display: "block", marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 }}>Report Period</label>

              {/* Presets */}
              <div style={{ display: "flex", gap: 8, marginBottom: 12 }}>
                {[
                  { label: "Last 15 days", days: 15 },
                  { label: "Last 30 days", days: 30 },
                  { label: "This month", days: 0, action: () => { setDateFrom(toInputDate(new Date(today.getFullYear(), today.getMonth(), 1))); setDateTo(toInputDate(today)); } },
                  { label: "Last month", days: 0, action: () => { const lm = new Date(today.getFullYear(), today.getMonth() - 1, 1); const lmEnd = new Date(today.getFullYear(), today.getMonth(), 0); setDateFrom(toInputDate(lm)); setDateTo(toInputDate(lmEnd)); } },
                ].map(p => (
                  <button key={p.label} onClick={() => p.action ? p.action() : setPreset(p.days)}
                    style={{ padding: "7px 14px", borderRadius: 7, border: `1px solid ${C.border}`, background: "transparent", color: C.cyan, fontSize: 11, fontWeight: 600, cursor: "pointer" }}>
                    {p.label}
                  </button>
                ))}
              </div>

              {/* Custom date pickers */}
              <div style={{ display: "grid", gridTemplateColumns: "1fr auto 1fr", gap: 10, alignItems: "center" }}>
                <div>
                  <label style={{ fontSize: 9, color: C.textMuted, display: "block", marginBottom: 4 }}>From</label>
                  <input type="date" value={dateFrom} onChange={e => setDateFrom(e.target.value)}
                    style={{ width: "100%", padding: "8px 10px", background: C.bg, border: `1px solid ${C.border}`, borderRadius: 7, color: C.text, fontSize: 12, outline: "none" }} />
                </div>
                <span style={{ fontSize: 14, color: C.textMuted, paddingTop: 16 }}>→</span>
                <div>
                  <label style={{ fontSize: 9, color: C.textMuted, display: "block", marginBottom: 4 }}>To</label>
                  <input type="date" value={dateTo} onChange={e => setDateTo(e.target.value)}
                    style={{ width: "100%", padding: "8px 10px", background: C.bg, border: `1px solid ${C.border}`, borderRadius: 7, color: C.text, fontSize: 12, outline: "none" }} />
                </div>
              </div>

              <div style={{ fontSize: 11, color: C.cyan, marginTop: 8, fontWeight: 600 }}>{periodLabel}</div>
            </div>

            {/* Bulk toggle */}
            <div style={{ display: "flex", gap: 8 }}>
              <button onClick={() => setBulkMode(!bulkMode)}
                style={{ padding: "7px 14px", borderRadius: 7, border: `1px solid ${bulkMode ? C.cyan : C.border}`, background: bulkMode ? `${C.cyan}15` : "transparent", color: bulkMode ? C.cyan : C.textMuted, fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
                {bulkMode ? "Single Mode" : "Bulk Mode"}
              </button>
            </div>

            {/* Bulk client selector */}
            {bulkMode && (
              <div style={{ marginTop: 14, borderTop: `1px solid ${C.border}`, paddingTop: 14 }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}>
                  <span style={{ fontSize: 12, color: C.textMuted }}>{selectedClients.length} clients selected</span>
                  <div style={{ display: "flex", gap: 6 }}>
                    <button onClick={() => setSelectedClients(clients.map(c => c.id))} style={{ fontSize: 10, color: C.cyan, background: "transparent", border: "none", cursor: "pointer", fontWeight: 600 }}>Select All</button>
                    <button onClick={() => setSelectedClients([])} style={{ fontSize: 10, color: C.textMuted, background: "transparent", border: "none", cursor: "pointer" }}>Clear</button>
                  </div>
                </div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                  {clients.map(c => (
                    <button key={c.id} onClick={() => toggleClient(c.id)}
                      style={{ padding: "5px 10px", borderRadius: 6, border: `1px solid ${selectedClients.includes(c.id) ? C.cyan : C.border}`, background: selectedClients.includes(c.id) ? `${C.cyan}15` : "transparent", color: selectedClients.includes(c.id) ? C.cyan : C.textMuted, fontSize: 11, cursor: "pointer" }}>
                      {c.businessName || c.name}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </Card>

          {/* Section filter */}
          <Card style={{ marginBottom: 16 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}>
              <label style={{ fontSize: 10, color: C.textMuted, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.5 }}>Sections to Include</label>
              <div style={{ display: "flex", gap: 6 }}>
                <button onClick={() => setVisibleSections(ALL_SECTIONS.map(s => s.id))} style={{ fontSize: 10, color: C.cyan, background: "transparent", border: "none", cursor: "pointer", fontWeight: 600 }}>All</button>
                <button onClick={() => setVisibleSections(["score", "reviews", "actions"])} style={{ fontSize: 10, color: C.textMuted, background: "transparent", border: "none", cursor: "pointer" }}>Minimal</button>
                <button onClick={() => setVisibleSections([])} style={{ fontSize: 10, color: C.textMuted, background: "transparent", border: "none", cursor: "pointer" }}>None</button>
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
              {ALL_SECTIONS.map(s => {
                const active = visibleSections.includes(s.id);
                return (
                  <button key={s.id} onClick={() => toggleSection(s.id)}
                    style={{ padding: "6px 12px", borderRadius: 7, border: `1px solid ${active ? C.cyan : C.border}`, background: active ? `${C.cyan}15` : "transparent", color: active ? C.cyan : C.textMuted, fontSize: 11, fontWeight: 600, cursor: "pointer", transition: "all .15s" }}>
                    {active ? "✓ " : ""}{s.label}
                  </button>
                );
              })}
            </div>
            <div style={{ marginTop: 8, fontSize: 10, color: C.textMuted }}>{visibleSections.length} of {ALL_SECTIONS.length} sections selected</div>
          </Card>

          {/* Generate */}
          <div style={{ display: "flex", justifyContent: "center" }}>
            <Btn onClick={bulkMode ? generateBulk : generate} disabled={generating || (bulkMode && selectedClients.length === 0)}>
              {generating ? "Generating..." : bulkMode ? `Generate ${selectedClients.length} Report${selectedClients.length > 1 ? "s" : ""}` : "Generate Report"}
            </Btn>
          </div>
        </>
      )}

      {/* Single report */}
      {report && !bulkReports.length && (
        <div>
          <div style={{ display: "flex", gap: 8, marginBottom: 16, justifyContent: "space-between", alignItems: "center" }}>
            <button onClick={() => setReport(null)}
              style={{ padding: "7px 14px", borderRadius: 7, border: `1px solid ${C.border}`, background: "transparent", color: C.textMuted, fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
              ← Back
            </button>
            <div style={{ display: "flex", gap: 8 }}>
              <button onClick={copyReport}
                style={{ padding: "7px 14px", borderRadius: 7, border: `1px solid ${C.border}`, background: "transparent", color: C.cyan, fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
                Copy Text
              </button>
              <button onClick={() => downloadReportPDF(report, visibleSections, periodLabel)}
                style={{ padding: "7px 14px", borderRadius: 7, border: `1px solid ${C.green}55`, background: `${C.green}15`, color: C.green, fontSize: 12, fontWeight: 700, cursor: "pointer" }}>
                Download PDF
              </button>
            </div>
          </div>
          {renderReport(report)}
        </div>
      )}

      {/* Bulk reports */}
      {bulkReports.length > 0 && (
        <div>
          <div style={{ display: "flex", gap: 8, marginBottom: 16, justifyContent: "space-between", alignItems: "center" }}>
            <button onClick={() => { setBulkReports([]); setSelectedClients([]); }}
              style={{ padding: "7px 14px", borderRadius: 7, border: `1px solid ${C.border}`, background: "transparent", color: C.textMuted, fontSize: 12, fontWeight: 600, cursor: "pointer" }}>
              ← Back
            </button>
            <span style={{ fontSize: 12, color: C.textMuted }}>{bulkReports.length} reports — {periodLabel}</span>
          </div>
          {bulkReports.map((br, i) => (
            <div key={br.client.id} style={{ marginBottom: 24 }}>
              <div style={{ fontSize: 11, color: C.textMuted, fontWeight: 600, marginBottom: 6, paddingBottom: 6, borderBottom: `1px solid ${C.border}` }}>
                Report {i + 1} of {bulkReports.length}
              </div>
              {renderReport(br.data)}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
