export const CLIENTS = [
  {
    id: "1", name: "MEL Home Building LLC", businessName: "MEL Home Building LLC",
    category: "Home Renovation Contractor", city: "Danbury", score: 68,
    address: "Danbury, CT 06810", verified: true, descriptionLength: 340,
    description: "MEL Home Building is a licensed general contractor in Danbury, CT with 26+ years of experience. We specialize in framing, siding, interior and exterior trim, kitchen remodeling, and bathroom renovations for residential homeowners across Connecticut and Westchester County, NY. Fully insured with General Liability and Workers Comp. Google Guaranteed.",
    secondaryCategories: ["Framing Contractor", "Siding Contractor", "Kitchen Remodeler"],
    services: ["Framing Contractors", "Siding Contractors", "Interior Trim Services", "Exterior Trim Services", "Bathroom Remodel", "Kitchen Remodeling", "Drywall", "Insulation", "Finish Carpentry"],
    website: "https://melhomebuildingct.com", phone: "(203) 635-6211",
    hours: { filled: true }, attributes: 9,
    photos: { total: 47, lastUpload: "2026-03-01", hasTeam: true, hasCoverPhoto: true, work: 18, interior: 12, exterior: 8, team: 5 },
    posts: [
      { date: "2026-03-05", type: "UPDATE", text: "With MEL Home Building, your home is in good hands." },
      { date: "2026-02-20", type: "UPDATE", text: "Tired of delays? We deliver on time, every time." },
    ],
    reviews: { total: 7, average: 5.0, withResponse: 5, last30days: 2, negativeUnanswered: 0,
      samples: [
        { author: "Thomas G.", text: "Great company, excellent quality. Anderson is a master carpenter with solutions for every problem." },
        { author: "Kevin R.", text: "Technical expertise is outstanding. Craftsmanship equally impressive. Fit, finish, attention to detail consistently excellent." },
        { author: "Samuel R.", text: "Quality of craftsmanship outstanding, exceeded expectations. Project completed on time, professional from start to finish." },
      ]
    },
    pendingTasks: 4, tags: ["Top Client", "Active"], rating: 5.0,
  },
  {
    id: "2", name: "Eletrica Nashua Pro", businessName: "Eletrica Nashua Pro",
    category: "Electrician", city: "Nashua", score: 42,
    address: "Nashua, NH 03060", verified: true, descriptionLength: 132,
    description: "We are an electrical company providing services in the Nashua area.",
    secondaryCategories: ["Residential Electrical"], services: ["Electrical Services", "Wiring", "Panel Upgrade"],
    website: "https://eletricanashua.com", phone: "+1 603-555-0100",
    hours: { filled: true }, attributes: 4,
    photos: { total: 11, lastUpload: "2024-11-15", hasTeam: false, hasCoverPhoto: true, work: 5, interior: 2, exterior: 2, team: 0 },
    posts: [{ date: "2025-01-18", type: "UPDATE", text: "Quality electrical services guaranteed!" }],
    reviews: { total: 38, average: 4.1, withResponse: 22, last30days: 1, negativeUnanswered: 2,
      samples: [
        { author: "John D.", text: "Good service, came on time." },
        { author: "Mary S.", text: "Fixed our outlet. Quick and professional." },
      ]
    },
    pendingTasks: 12, tags: ["Needs Work"], rating: 4.1,
  },
  {
    id: "3", name: "JC Digital Marketing Agency", businessName: "JC Digital Marketing Agency",
    category: "Digital Marketing Agency", city: "Boston", score: 65,
    address: "Boston, MA 02101", verified: true, descriptionLength: 420,
    description: "JC Digital is a full-service digital marketing agency in Boston specializing in Local SEO, Google Business Profile optimization, and semantic engineering for local businesses across the USA. We help contractors, dentists, lawyers and service businesses dominate local search results.",
    secondaryCategories: ["SEO Local", "Google Business Profile"], services: ["Local SEO", "GBP Optimization", "Website Design", "Content Marketing"],
    website: "https://jcdigitalexpand.com", phone: "+1 617-555-0300",
    hours: { filled: true }, attributes: 6,
    photos: { total: 8, lastUpload: "2024-10-01", hasTeam: true, hasCoverPhoto: false, work: 2, interior: 1, exterior: 0, team: 3 },
    posts: [{ date: "2025-02-01", type: "UPDATE", text: "New local SEO success case!" }],
    reviews: { total: 22, average: 4.9, withResponse: 22, last30days: 2, negativeUnanswered: 0,
      samples: [
        { author: "Client A.", text: "JC Digital transformed our Google presence. More leads than ever." },
        { author: "Client B.", text: "Best SEO agency. They understand local search deeply." },
      ]
    },
    pendingTasks: 5, tags: ["Agency"], rating: 4.9,
  },
  {
    id: "4", name: "Bright Smiles Dental Care", businessName: "Bright Smiles Dental Care",
    category: "Dentist", city: "Orlando", score: 85,
    address: "Orlando, FL 32801", verified: true, descriptionLength: 510,
    description: "Bright Smiles Dental Care is a family dental practice in Orlando, FL offering comprehensive preventive, cosmetic, and restorative dentistry. Our licensed dentists serve patients of all ages with gentle care, flexible scheduling, and same-day emergency appointments. We accept most major insurance plans. Located near Downtown Orlando, serving Orange County.",
    secondaryCategories: ["Cosmetic Dentist", "Emergency Dental Service"],
    services: ["General Dentistry", "Teeth Whitening", "Dental Implants", "Invisalign", "Emergency Dental Care"],
    website: "https://brightsmilesdentalorlando.com", phone: "(407) 555-0200",
    hours: { filled: true }, attributes: 11,
    photos: { total: 34, lastUpload: "2026-02-15", hasTeam: true, hasCoverPhoto: true, work: 12, interior: 10, exterior: 4, team: 8 },
    posts: [
      { date: "2026-02-28", type: "OFFER", text: "Spring whitening special — $199 in-office treatment this month only!" },
      { date: "2026-02-10", type: "UPDATE", text: "New Invisalign certified provider in Orlando." },
    ],
    reviews: { total: 142, average: 4.8, withResponse: 138, last30days: 8, negativeUnanswered: 0,
      samples: [
        { author: "Sarah K.", text: "Best dental experience I've had. Dr. Chen is incredibly gentle and thorough." },
        { author: "Marcus T.", text: "Emergency appointment on a Saturday — they fit me in within 2 hours. Exceptional service." },
        { author: "Linda R.", text: "Invisalign results are amazing. The whole team was supportive throughout the process." },
      ]
    },
    pendingTasks: 2, tags: ["Top Client", "High Performer"], rating: 4.8,
  },
  {
    id: "5", name: "Rodriguez Family Law", businessName: "Rodriguez Family Law",
    category: "Family Law Attorney", city: "Miami", score: 72,
    address: "Miami, FL 33101", verified: true, descriptionLength: 390,
    description: "Rodriguez Family Law is a bilingual law firm in Miami, FL specializing in divorce, child custody, and family legal matters. Attorney Maria Rodriguez has 18+ years of experience serving English and Spanish-speaking clients across Miami-Dade County. We offer free initial consultations and flexible payment plans.",
    secondaryCategories: ["Divorce Lawyer", "Child Custody Attorney"],
    services: ["Divorce", "Child Custody", "Alimony", "Prenuptial Agreements", "Domestic Violence Protection"],
    website: "https://rodriguezfamilylaw.com", phone: "(305) 555-0400",
    hours: { filled: true }, attributes: 7,
    photos: { total: 14, lastUpload: "2025-12-10", hasTeam: true, hasCoverPhoto: true, work: 2, interior: 6, exterior: 1, team: 5 },
    posts: [{ date: "2026-01-20", type: "UPDATE", text: "Understanding your rights in Florida custody cases. Free consultation available." }],
    reviews: { total: 67, average: 4.7, withResponse: 65, last30days: 3, negativeUnanswered: 0,
      samples: [
        { author: "Elena V.", text: "Maria guided me through a very difficult divorce with compassion and expertise." },
        { author: "James P.", text: "Won my custody case. Attorney Rodriguez is brilliant and truly cares about her clients." },
      ]
    },
    pendingTasks: 6, tags: ["Active"], rating: 4.7,
  },
  {
    id: "6", name: "Peak Performance HVAC", businessName: "Peak Performance HVAC",
    category: "HVAC Contractor", city: "Phoenix", score: 74,
    address: "Phoenix, AZ 85001", verified: true, descriptionLength: 280,
    description: "Peak Performance HVAC serves Phoenix and surrounding areas with expert AC installation, repair, and maintenance. Licensed Arizona HVAC contractor with NATE-certified technicians. Emergency 24/7 service available.",
    secondaryCategories: ["Air Conditioning Repair", "Heating Contractor"],
    services: ["AC Installation", "AC Repair", "Furnace Repair", "Duct Cleaning", "HVAC Maintenance"],
    website: "https://peakperformancehvac.com", phone: "(602) 555-0500",
    hours: { filled: true }, attributes: 8,
    photos: { total: 22, lastUpload: "2026-01-30", hasTeam: false, hasCoverPhoto: true, work: 14, interior: 3, exterior: 3, team: 0 },
    posts: [{ date: "2026-02-25", type: "UPDATE", text: "Summer is coming! Schedule your AC tune-up now and avoid the rush." }],
    reviews: { total: 89, average: 4.6, withResponse: 80, last30days: 5, negativeUnanswered: 1,
      samples: [
        { author: "Bob H.", text: "Fixed our AC in under 2 hours on a 115-degree day. Lifesavers!" },
        { author: "Carol M.", text: "Honest pricing, quality work. Replaced our entire system efficiently." },
      ]
    },
    pendingTasks: 3, tags: ["Active"], rating: 4.6,
  },
  {
    id: "7", name: "GreenLeaf Landscaping", businessName: "GreenLeaf Landscaping",
    category: "Landscaping Company", city: "Austin", score: 28,
    address: "Austin, TX 78701", verified: false, descriptionLength: 180,
    description: "GreenLeaf Landscaping provides lawn care, tree trimming, and landscape design services in Austin, TX. Call us for a free estimate.",
    secondaryCategories: ["Lawn Care Service"],
    services: ["Lawn Mowing", "Tree Trimming", "Landscape Design", "Irrigation Systems"],
    website: "", phone: "(512) 555-0600",
    hours: { filled: false }, attributes: 3,
    photos: { total: 6, lastUpload: "2025-08-10", hasTeam: false, hasCoverPhoto: false, work: 4, interior: 0, exterior: 1, team: 0 },
    posts: [],
    reviews: { total: 11, average: 3.9, withResponse: 4, last30days: 0, negativeUnanswered: 3,
      samples: [
        { author: "Tom B.", text: "Did an okay job on the lawn but left a mess." },
        { author: "Lisa A.", text: "Showed up 2 hours late but the work was decent." },
      ]
    },
    pendingTasks: 18, tags: ["Needs Work", "Urgent"], rating: 3.9,
  },
  {
    id: "8", name: "CloudPoint IT Solutions", businessName: "CloudPoint IT Solutions",
    category: "IT Services & Computer Repair", city: "Seattle", score: 76,
    address: "Seattle, WA 98101", verified: true, descriptionLength: 460,
    description: "CloudPoint IT Solutions is a managed IT services provider in Seattle, WA serving small and mid-size businesses. We offer 24/7 network monitoring, cybersecurity, cloud migration, and helpdesk support. Microsoft Gold Partner with CISSP-certified engineers serving King County and Greater Seattle.",
    secondaryCategories: ["Computer Support & Services", "Network Security Service"],
    services: ["Managed IT Services", "Cybersecurity", "Cloud Migration", "Helpdesk Support", "Network Setup"],
    website: "https://cloudpointit.com", phone: "(206) 555-0700",
    hours: { filled: true }, attributes: 10,
    photos: { total: 18, lastUpload: "2026-01-15", hasTeam: true, hasCoverPhoto: true, work: 8, interior: 5, exterior: 1, team: 4 },
    posts: [
      { date: "2026-03-01", type: "UPDATE", text: "New cybersecurity audit service launched. Protect your Seattle business from ransomware." },
      { date: "2026-02-15", type: "UPDATE", text: "Microsoft 365 migration specialists in Seattle." },
    ],
    reviews: { total: 53, average: 4.7, withResponse: 50, last30days: 4, negativeUnanswered: 0,
      samples: [
        { author: "Alex P.", text: "CloudPoint migrated our entire infrastructure to Azure. Zero downtime." },
        { author: "Diana W.", text: "Best IT partner we've had. Proactive monitoring caught a breach attempt before it happened." },
      ]
    },
    pendingTasks: 3, tags: ["Active"], rating: 4.7,
  },
  {
    id: "9", name: "Sunrise Plumbing & Drain", businessName: "Sunrise Plumbing & Drain",
    category: "Plumber", city: "Denver", score: 71,
    address: "Denver, CO 80201", verified: true, descriptionLength: 320,
    description: "Sunrise Plumbing & Drain is a licensed plumber in Denver, CO specializing in drain cleaning, pipe repair, water heater installation, and emergency plumbing. We serve residential and commercial clients across Denver Metro. Upfront pricing with no surprise fees.",
    secondaryCategories: ["Drain Cleaning Service", "Water Heater Repair"],
    services: ["Drain Cleaning", "Pipe Repair", "Water Heater Installation", "Emergency Plumbing", "Sewer Line Inspection"],
    website: "https://sunriseplumbingdenver.com", phone: "(720) 555-0800",
    hours: { filled: true }, attributes: 7,
    photos: { total: 29, lastUpload: "2026-02-20", hasTeam: false, hasCoverPhoto: true, work: 18, interior: 5, exterior: 3, team: 0 },
    posts: [{ date: "2026-03-03", type: "UPDATE", text: "Frozen pipe repair specialists in Denver. 24/7 emergency response." }],
    reviews: { total: 78, average: 4.5, withResponse: 70, last30days: 6, negativeUnanswered: 1,
      samples: [
        { author: "Mike L.", text: "Fixed a burst pipe at 2am. Fast, professional, fair price." },
        { author: "Janet C.", text: "Cleared a severe drain blockage same day. Honest about what needed to be done." },
      ]
    },
    pendingTasks: 4, tags: ["Active"], rating: 4.5,
  },
  {
    id: "10", name: "Luxe Auto Detailing", businessName: "Luxe Auto Detailing",
    category: "Car Detailing Service", city: "Las Vegas", score: 82,
    address: "Las Vegas, NV 89101", verified: true, descriptionLength: 240,
    description: "Luxe Auto Detailing in Las Vegas offers premium mobile car detailing, paint correction, ceramic coating, and interior deep clean. We come to your home or office. Serving Henderson, Summerlin, and the Las Vegas Strip area.",
    secondaryCategories: ["Auto Detailing", "Car Wash"],
    services: ["Mobile Detailing", "Ceramic Coating", "Paint Correction", "Interior Deep Clean", "Engine Bay Cleaning"],
    website: "https://luxeautodetailinglv.com", phone: "(702) 555-0900",
    hours: { filled: true }, attributes: 6,
    photos: { total: 41, lastUpload: "2026-03-08", hasTeam: true, hasCoverPhoto: true, work: 28, interior: 6, exterior: 4, team: 3 },
    posts: [
      { date: "2026-03-08", type: "UPDATE", text: "Fresh ceramic coating job on a Ferrari 488. See the transformation!" },
      { date: "2026-02-22", type: "OFFER", text: "Spring detail special — full detail + ceramic coat from $299. Limited slots." },
    ],
    reviews: { total: 96, average: 4.9, withResponse: 96, last30days: 9, negativeUnanswered: 0,
      samples: [
        { author: "Chris V.", text: "My car looks better than the day I bought it. Absolute perfection." },
        { author: "Stephanie R.", text: "Best detailing in Vegas. The ceramic coat is incredible — water just beads off." },
      ]
    },
    pendingTasks: 1, tags: ["Top Client", "High Performer"], rating: 4.9,
  },
];
